services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=banco_etl
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:latest
    container_name: meu_airflow
    ports:
      - "8080:8080"
    # standalone faz rodar em um unico comando simples
    command: standalone

volumes:
  # cria a pasta virtual para os dados nao sumirem se reiniciar o computador
  postgres_data: